### ISSUE TITLE
Fix default route explanation for HTTP traffic

### ISSUE THREAD

**Issue by lautou** [RedHatQuickCourses/rhods-intro#23]
Chapter 2 - Section 2: Workbench Resources
It is said :
`RHODS also creates the required services and routes to enable HTTP and HTTPS traffic into the workbench container.`

In reality (checked with ODS 2.4.0), only one HTTPS route is created with non-secure traffic configured (HTTP) to be redirected to HTTPS (`insecureEdgeTerminationPolicy: Redirect`).
The architecture diagram below shows an edge from Route to Service port 80 for HTTP traffic but it will never happen.
HTTP traffic will be redirected to TLS Service port 443.

You should fix both the text and the diagram to reflect this behavior.

**Comment by rsriniva** [comment]
until diagram is fixed - will add a sentence about HTTP->HTTPS redirection
