### ISSUE TITLE
Need to cover models types and serving engines

### ISSUE THREAD

**Issue by noelo** [RedHatQuickCourses/rhods-intro#29]
OVMS - OpenVino, ONNA, Triton
MLserver - xgboost, sklearn, lightbgm

What they do, what benefits and when to use them.

**Comment by rsriniva** [comment]
not sure if this would be overkill for this intro - maybe talk about these in the model deployment course?

**Comment by jramcast** [comment]
I've just copied this issue into the deployment course https://github.com/RedHatQuickCourses/rhods-deploy/issues/18
