### ISSUE TITLE
Inconsistent references to final lab

### ISSUE THREAD

**Issue by rsriniva** [RedHatQuickCourses/rhods-intro#34]
Some courses home page calls it HIt the RHODS, some Hit the RHOAI and some just say Workshop final lab. Keep the naming consistent in the INFO admonition in the home page of the five courses

**Comment by jramcast** [comment]
Considering that the RHODS naming is now deprecated, and also considering that _Hit the RHOAI_ does not make any sense, I'd suggest renaming all the references to something like "Workshop final lab". @rsriniva WDYT?

**Comment by rsriniva** [comment]
text has been updated to reflect the new naming for the final lab
