### ISSUE TITLE
No admin access to groups with RHOAI sandbox

### ISSUE THREAD

**Issue by jdandrea** [RedHatQuickCourses/rhods-intro#36]
Using an [RHOAI sandbox](https://console.redhat.com/application-services/data-science) as instructed by the course, in the [Chapter 2 Lab](https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter2/section4.html) we are instructed to create a group by logging in as an administrator and applying a group YAML file. However, our lone account, while it appears to have administrator access, is still restricted from listing or creating groups:

```
bash-4.4 ~ $ oc get groups
Error from server (Forbidden): groups.user.openshift.io is forbidden: User "rhn-gps-jdandrea" cannot list resource "groups" in API group "user.openshift.io" at the cluster scope
```

Is there another step we missed somewhere?

**Comment by jdandrea** [comment]
Side note: To get an S3 bucket (also part of this same section), I was directed to use [step 1 of section 2.3.2 of the OpenShift AI Fraud Detection example](https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_cloud_service/1/html/openshift_ai_tutorial_-_fraud_detection_example/setting-up-a-project-and-storage#running-a-script-to-install-storage). That seems to have worked, but the RBAC issues remain.

**Comment by jdandrea** [comment]
Checking in. Still unable to create users and groups in a Developer Sandbox, which is what's recommended by [Introduction to Red Hat OpenShift AI](https://redhatquickcourses.github.io/rhods-intro/). It is required by the [Assessment Lab: Working with Data Science Projects](https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter2/section4.html). How are others completing this?

**Comment by rsriniva** [comment]
@jdandrea - we initially suggested the sandbox to save some costs. Please fire up the alternate RHDP environment to do some of the labs that involve cluster admin functionality

@jramcast @stencell - propose we remove the sandbox option to avoid confusing people. Due to the organic growth of the hands on labs and ad-hoc functionality additions after the initial round of testing, it looks like sandbox won't work for us anymore.

**Comment by jdandrea** [comment]
RHDP - ahaa, I will investigate. Thank you so much! 

(Will leave this open so that the sandbox option can be removed from the text and associated with this.)

**Comment by stencell** [comment]
@rsriniva Yes, please remove it if it doesn't work. Please add a recommended RHDP catalog item in it's place. It should ideally be something that is very generic - a vanilla OpenShift cluster with OpenShift AI installed. If you need to break that out into another issue to track, please do so.

**Comment by rsriniva** [comment]
@jdandrea - I am sorry you have had so many issues with the classroom. Please use this catalog item for the hands on labs for this course - https://demo.redhat.com/catalog?search=openshift+data+science&item=babylon-catalog-prod%2Fsandboxes-gpte.ocp4-workshop-rhods-base-aws.prod

The other courses ask you to launch a different RHDP catalog item. Please delete and stop classrooms when not in use to help manage capacity effectively. Thank you!

**Comment by jdandrea** [comment]
@rsriniva that's excellent, thank you so much!

I'm going to give it a whirl and report back.

**Comment by rsriniva** [comment]
Text has been updated on the home page to reflect the correct classroom. I am closing this issue. Please open a new issue for classroom issues still persist
