### ISSUE TITLE
Issue with rhods-qc-apps/1.intro/chapter1/intro-text-generation/notebook.ipynb in Demo

### ISSUE THREAD

**Issue by sarveshpandit** [RedHatQuickCourses/rhods-intro#48]
`rhods-qc-apps/1.intro/chapter1/intro-text-generation/notebook.ipynb` Is not working.

 I get this error - "ls: cannot access 'my_model/pytorch_model.bin': No such file or directory"

**Comment by rsriniva** [comment]
@sarveshpandit - did you see an error similar to this in your QA?

**Comment by rsriniva** [comment]
@jramcast - any quick ideas?

**Comment by gjbianco** [comment]
Did you follow the instructions in the cell prior to that `%ls` command? :slightly_smiling_face:

**Comment by sarveshpandit** [comment]
Yes, I followed and waited for it to complete too.

**Comment by rsriniva** [comment]
works as written. @sarveshpandit - you need to download the pytorch_model.bin file from google drive and upload it to a specific folder in the workbench. After you do this, the exercise works as written. the ls -l command in the notebook should show a 312MB model bin file as output before you can proceed with running the model

**Comment by sarveshpandit** [comment]
Looks good
