### ISSUE TITLE
No video with supported format and MIME type found.

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-intro#56]
Page https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter3/section1.html says

> If you cannot run the previous exercises, you can see the following demo:

However, on Firefox 122 (on Fedora 39), there is no video shown, just a grey error rectangle with message

> No video with supported format and MIME type found.

I't because Firefox does not support video/x-matroska:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1422891
- https://connect.mozilla.org/t5/ideas/add-support-for-matroska-media-container-mkv-files/idi-p/15935

Please publish the ./modules/chapter3/images/jupyter-intro.mkv video in a format understood by the default RHEL browser.

**Comment by rsriniva** [comment]
thanks for reporting this @adelton. I think we can upload the mkv to youtube and link it in the adoc? would this be acceptable to you?

**Comment by adelton** [comment]
My personal preference does not really matter. :-)

If this course is served via https://start.learning.redhat.com/ then I'd say the standards of that platform around video formats / MIME types should be the definitive guidance.

**Comment by rsriniva** [comment]
fixed in main. replaced mkv file with youtube.
