### ISSUE TITLE
Problems with OpenShift AI sandbox without settings and the storage is insufficient

### ISSUE THREAD

**Issue by Loredufa** [RedHatQuickCourses/rhods-intro#62]
Inside the sandbox, I cannot access the settings options to upload my custom images; therefore, the pipeline exercises cannot be completed.
![Captura de pantalla 2024-05-21 170403](https://github.com/RedHatQuickCourses/rhods-intro/assets/88742175/a8127b4f-19ad-46ba-a4c9-d14b72bfb6e7)
Additionally, to perform the exercises, both MinIO consumes 20Gi and the workbench is created with 20Gi, and since OpenShift only has 40Gi of storage, it is not possible to deploy the model or add a pipeline.

**Comment by rsriniva** [comment]
We do not recommend using the sandbox for this course. Please see front page of the course (course #2 in the learning path on RHOAI admin) and provision the correct classroom

**Comment by kknoxrht** [comment]
Hello,  I know it's been a while, but taking on the OpenShift AI Issues,   wanted to share a couple of suggestions.

Change the settings of Minio to use less storage -  You can find the setting in the image attached:

depending on the model size, 10Gb should work in most cases.

<img width="678" alt="minio_storage" src="https://github.com/user-attachments/assets/3c20e958-c00a-4c8f-8b34-0cee631bf557">

You can also change the persistent volume for Cluster storage when creating the Workbench to as low as 2GB, this is not for model hosting or pipelines, those both use the Minio storage.  Simply use reduce the option during workbench creation.  If your going to clone large repositories you will need to up this storage to meet your needs.

<img width="724" alt="cluster storage" src="https://github.com/user-attachments/assets/efd437d3-81b0-4f10-b540-d5c6ce8efaaa">

Thanks for learning OpenShift AI and good luck.
